# Generated by Django 5.0.1 on 2024-01-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_wallet_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='icon',
        ),
    ]
